import {
  LayoutDashboard,
  MessageSquare,
  Search,
  UserPlus,
  Link2 as Paperclip,
  Foot as FootIcon,
  Box,
  Package,
  Mail,
  Calendar,
  BarChart3,
  Users,
  Zap,
  FileText,
  Settings,
  ShoppingBag,
  Package2,
  Activity,
} from "lucide-react";

// Menu items with icons - matching the sidebar
export const menuItems = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    route: "/dashboard",
  },
  {
    id: "teamchat",
    label: "Teamchat",
    icon: MessageSquare,
    route: "/dashboard/teamchat",
  },
  {
    id: "kundensuche",
    label: "Kundensuche",
    icon: Search,
    route: "/dashboard/kundensuche",
  },
  {
    id: "neukundenerstellung",
    label: "Neukundenerstellung",
    icon: UserPlus,
    route: "/dashboard/neukundenerstellung",
  },
  {
    id: "einlagenauftrage",
    label: "Einlagenaufträge",
    icon: Paperclip,
    route: "/dashboard/einlagenauftrage",
  },
  {
    id: "massschuhauftrage",
    label: "Maßschuhaufträge",
    icon: ShoppingBag,
    route: "/dashboard/massschuhauftrage",
  },
  {
    id: "massschafte",
    label: "Maßschäfte",
    icon: Package2,
    route: "/dashboard/massschafte",
  },
  {
    id: "produktverwaltung",
    label: "Produktverwaltung",
    icon: Box,
    route: "/dashboard/produktverwaltung",
  },
  {
    id: "sammelbestellungen",
    label: "Sammelbestellungen",
    icon: Package,
    route: "/dashboard/sammelbestellungen",
  },
  {
    id: "nachrichten",
    label: "Nachrichten",
    icon: Mail,
    route: "/dashboard/nachrichten",
  },
  {
    id: "terminkalender",
    label: "Terminkalender",
    icon: Calendar,
    route: "/dashboard/terminkalender",
  },
  {
    id: "monatsstatistik",
    label: "Monatsstatistik",
    icon: BarChart3,
    route: "/dashboard/monatsstatistik",
  },
  {
    id: "mitarbeitercontrolling",
    label: "Mitarbeitercontrolling",
    icon: Users,
    route: "/dashboard/mitarbeitercontrolling",
  },
  {
    id: "einlagencontrolling",
    label: "Einlagencontrolling",
    icon: Zap,
    route: "/dashboard/einlagencontrolling",
  },
  {
    id: "fuubungen",
    label: "Fußübungen",
    icon: Activity,
    route: "/dashboard/fuubungen",
  },
  {
    id: "musterzettel",
    label: "Musterzettel",
    icon: FileText,
    route: "/dashboard/musterzettel",
  },
  {
    id: "einstellungen",
    label: "Einstellungen",
    icon: Settings,
    route: "/dashboard/settings",
  },
];
